### PR TITLE
Init command

### PR DESCRIPTION
**Pull request by fg1989**
Necessaire de merge #34 avant de merge cette branche

### CODE REVIEW

**Comment by fg1989** [comment]
#22

**Comment by fg1989** [comment]
#22

**Comment by roosemberth** [comment]
@fg1989 #34 has been merged. Can you please rebase this on master and drop babaf20e0fe72375b5fdb4ab14ec1d3d45648cca?

**Review by Quillasp — APPROVED** [review]
Tout bon pour moi

**Pull request merged**
